# Generated by Django 4.1.5 on 2023-01-28 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "citizenship_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "citizenship",
                    models.ImageField(
                        default="default_photo.jpg", upload_to="enduser/profile"
                    ),
                ),
                ("license_no", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "license",
                    models.ImageField(
                        default="default_photo.jpg", upload_to="enduser/profile"
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        default="default_profile.jpg", upload_to="enduser/profile"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enduser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "citizenship_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "citizenship",
                    models.ImageField(
                        default="default_photo.jpg", upload_to="host/profile"
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        default="default_profile.jpg", upload_to="host/profile"
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=20, unique=True)),
                ("bluebook", models.ImageField(upload_to="host/vehicle")),
                ("bluebook_id", models.CharField(max_length=25)),
                ("image1", models.ImageField(upload_to="host/vehicle")),
                ("image2", models.ImageField(upload_to="host/vehicle")),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="host/vehicle"),
                ),
                ("description", models.CharField(max_length=2000)),
                ("feature", models.CharField(max_length=1000)),
                ("price", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Jeep", "Jeep"),
                            ("Mini-Van", "Mini-Van"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="base.host",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place",
                        to="base.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Travelogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=10000)),
                ("image1", models.ImageField(upload_to="enduser/travelogue")),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="enduser/travelogue"
                    ),
                ),
                (
                    "enduser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogger",
                        to="base.enduser",
                    ),
                ),
            ],
        ),
    ]
