# Generated by Django 4.1.5 on 2023-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelogue",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="enduser",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
