# Generated by Django 4.1.5 on 2023-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="citizenship_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="phone_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
