# Generated by Django 4.1.5 on 2023-03-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelogue",
            name="description",
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="feature",
            field=models.TextField(max_length=500),
        ),
    ]
