# Generated by Django 4.1.5 on 2023-01-07 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_remove_host_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="EndUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "citizenship_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("citizenship", models.ImageField(blank=True, null=True, upload_to="")),
                ("license_no", models.CharField(blank=True, max_length=20, null=True)),
                ("license", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enduser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
