# Generated by Django 4.1.5 on 2023-02-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_vehicle_description_alter_vehicle_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_rented",
            field=models.BooleanField(default=False),
        ),
    ]
