# Generated by Django 4.1.5 on 2023-03-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_enduser_is_blocked_host_is_blocked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enduser",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="raterent",
            name="rent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate",
                to="base.rents",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("NoAction", "NoAction"),
                    ("Warning", "Warning"),
                    ("Blocked", "Blocked"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="travelogue",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
