# Generated by Django 4.1.5 on 2023-01-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_enduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="enduser",
            name="pic",
            field=models.ImageField(
                default="default_profile.png", upload_to="enduser/profile"
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="pic",
            field=models.ImageField(
                default="default_profile.png", upload_to="host/profile"
            ),
        ),
        migrations.AlterField(
            model_name="enduser",
            name="citizenship",
            field=models.ImageField(blank=True, null=True, upload_to="enduser/profile"),
        ),
        migrations.AlterField(
            model_name="enduser",
            name="license",
            field=models.ImageField(blank=True, null=True, upload_to="enduser/profile"),
        ),
        migrations.AlterField(
            model_name="host",
            name="citizenship",
            field=models.ImageField(blank=True, null=True, upload_to="host/profile"),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=20, unique=True)),
                ("bluebook", models.ImageField(upload_to="host/vehicle")),
                ("bluebook_id", models.CharField(max_length=25)),
                ("image1", models.ImageField(upload_to="host/vehicle")),
                ("image2", models.ImageField(upload_to="host/vehicle")),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="host/vehicle"),
                ),
                ("description", models.CharField(max_length=2000)),
                ("feature", models.CharField(max_length=1000)),
                ("price", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Sedan", "Sedan"),
                            ("SUV", "SUV"),
                            ("Jeep", "Jeep"),
                            ("Mini-Van", "Mini-Van"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="base.host",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="place",
                        to="base.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Travelogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=10000)),
                ("image1", models.ImageField(upload_to="enduser/travelogue")),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="enduser/travelogue"
                    ),
                ),
                (
                    "enduser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogger",
                        to="base.enduser",
                    ),
                ),
            ],
        ),
    ]
