# Generated by Django 4.1.5 on 2023-03-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_enduser_is_approved_alter_host_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raterent",
            name="rent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate",
                to="base.rents",
            ),
        ),
    ]
