# Generated by Django 4.1.5 on 2023-01-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_location_enduser_pic_host_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="host",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="enduser",
            name="pic",
            field=models.ImageField(
                default="default_profile.jpg", upload_to="enduser/profile"
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="pic",
            field=models.ImageField(
                default="default_profile.jpg", upload_to="host/profile"
            ),
        ),
    ]
