# Generated by Django 4.1.5 on 2023-03-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_raterent_rent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enduser",
            name="phone_number",
            field=models.CharField(default="980000000000", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="host",
            name="phone_number",
            field=models.CharField(default=980, max_length=10),
            preserve_default=False,
        ),
    ]
