# Generated by Django 4.1.5 on 2023-03-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_enduser_phone_number_alter_host_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField(max_length=250)),
            ],
        ),
    ]
