# Generated by Django 4.1.5 on 2023-02-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_reportuser_ratevehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateRent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3
                    ),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="base.rents",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="RateVehicle",),
    ]
