# Generated by Django 4.1.5 on 2023-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_faqs"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy", models.CharField(max_length=100)),
                ("explanation", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=100)),
                ("explanation", models.TextField(max_length=250)),
            ],
        ),
    ]
