# Generated by Django 4.1.5 on 2023-03-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
