# Generated by Django 4.1.5 on 2023-04-09 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_transaction_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="rents", name="t_id",),
        migrations.AlterField(
            model_name="travelogue",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
