# Generated by Django 4.1.5 on 2023-04-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_rentrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="rentrequest", name="isapproved",),
    ]
