# Generated by Django 4.1.5 on 2023-04-10 14:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_remove_rentrequest_isapproved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle", name="feature", field=ckeditor.fields.RichTextField(),
        ),
    ]
